name: Bespoke psychotherapist
favicon: null
layout_spectrum: 0.5004403926432133
typography_spectrum: 0.5827752009499818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.980104573071003
  lightness: 0.576178326504305
  saturation: 0.661953465314582
  rhythmicContrast: 0.8181944701354951
purpose: []
